# Generated by Django 3.0.3 on 2020-03-28 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching_unsafe_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafe_codes',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsafe_codes',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searching_unsafe_codes.Languages'),
        ),
        migrations.AddField(
            model_name='unsafe_codes',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searching_unsafe_codes.Statuses'),
        ),
        migrations.AddField(
            model_name='statuses',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settings',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languages',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history_unsafe_code',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searching_unsafe_codes.History_repositories'),
        ),
        migrations.AddField(
            model_name='history_repositories',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searching_unsafe_codes.History'),
        ),
        migrations.AddField(
            model_name='history_repositories',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searching_unsafe_codes.Languages'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
