# Generated by Django 3.0.3 on 2020-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching_unsafe_codes', '0002_auto_20200328_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='path_to_token',
            field=models.CharField(default='C:\\Users\\fomin\\PycharmProjects\\HW20_Django_UnsafeCodesGitHub\\unsafe_codes_github\\GitHub_Token', max_length=15),
        ),
    ]
