# Generated by Django 3.0.3 on 2020-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching_unsafe_codes', '0003_auto_20200423_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_repositories',
            name='repository',
            field=models.TextField(blank=True),
        ),
    ]
