# Generated by Django 3.0.3 on 2020-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching_unsafe_codes', '0004_history_repositories_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='repository_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
