# Generated by Django 3.0.3 on 2020-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching_unsafe_codes', '0006_auto_20200424_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_settings',
            field=models.ManyToManyField(to='searching_unsafe_codes.Unsafe_codes'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
